version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: prm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/cstsortan/prm/cmd.version={{.Version}} -X github.com/cstsortan/prm/cmd.commit={{.ShortCommit}} -X github.com/cstsortan/prm/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "prm_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: cstsortan
    name: prm
